mp.jwt.verify.publickey.location=/publicKey.pem
mp.jwt.verify.issuer=https://grocery.local/auth

grocery.jwt.issuer=https://grocery.local/auth
grocery.jwt.private-key-location=/config/privateKey.pem
grocery.jwt.expiry-seconds=28800
